FROM aquasec/trivy:latest

ENV http_proxy 'http://10.64.42.200:3128'
ENV https_proxy 'http://10.64.42.200:3128'

RUN apk update
RUN apk --no-cache add curl
RUN apk --no-cache add docker openrc
RUN rc-update add docker boot


RUN adduser -D -u 1004 dmsis 

RUN addgroup docker && addgroup dmsis docker

RUN mkdir -p .cache
RUN chmod -R 777 .cache



ENTRYPOINT []
